name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Anilist metrics
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.anilist.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: Zeide
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 2
          plugin_anilist_shuffle: yes
